name: Docker Build & Validate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cesizen:latest

  validate:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ needs.docker.outputs.build-success == 'true' }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull and validate image
        run: |
          # Pull the image that was just built
          docker pull ${{ secrets.DOCKER_USERNAME }}/cesizen:latest
          # Quick validation that the image exists and can be inspected
          docker inspect ${{ secrets.DOCKER_USERNAME }}/cesizen:latest
          echo "✅ Docker image validated successfully"
